title: TARDIS
baseURL: https://tardis-sn.github.io/
params:
  base_font: nunito-sans
  palette: blue
  favicon: images/tardis_logo.ico
  header:
    logo_img: images/tardis-logo-2.svg
    logo_img_alt: Logo
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Documentation
        url: /documentation
        style: dropdown
        sub_items:
          - label: TARDIS
            url: https://tardis-sn.github.io/tardis
            style: redirect-link
          - label: Carsus
            url: https://tardis-sn.github.io/carsus
            style: redirect-link
      - label: Team
        url: /team
        style: dropdown
        sub_items:
          - label: Community Roles
            url: /team/community_roles
            style: dropdown-link
          - label: Collaboration
            url: /team/collaboration
            style: dropdown-link
          - label: Governance
            url: team/governance
            style: dropdown-link
      - label: Research
        url: /research
        style: dropdown
        sub_items: 
          - label: Papers
            url: /research/papers
            style: dropdown-link 
          - label: Presentations
            url:  /research/presentations
            style: dropdown-link
      - label: Credits
        url: /credits
        style: link
#      - label: News
#        url: /news
#        style: link #primary is another style available
  footer:
    sections:
      - type: footer_text
        image: images/tardis-banner-2.svg
        image_url: /
        image_alt: TARDIS Banner
      - type: footer_nav
        nav_links:
          - label: Code Of Conduct
            url: /code_of_conduct
            style: link
          - label: Sponsors
            url: /sponsors
            style: link
#          - label: Mission
#            url: /signup
#            style: link
      - type: footer_nav
        nav_links:
          - label: Twitter
            url: "https://twitter.com/tardis_sn"
            style: link
            has_icon: true
            icon: twitter
            icon_position: left
          - label: GitHub
            url: "https://github.com/tardis-sn"
            style: link
            has_icon: true
            icon: github
            icon_position: left
          - label: Gitter
            url: "https://gitter.im/tardis-sn/tardis"
            style: link
            has_icon: true
            icon: gitter
            icon_position: left
      - type: footer_text
        image: images/Numfocus_stamp.png
        image_url: "https://numfocus.org/project/tardis"
#    has_nav: true
#    nav_links:
#      - label: Terms of Service
#        url: /terms-of-service
#        style: link
#      - label: Privacy Policy
#        url: /privacy-policy
#        style: link
    content: >-
       Made with ❤️ using <a href="https://gohugo.io/" target="_blank" rel="noopener nofollow">Hugo</a> 
       and the <a href="https://themes.stackbit.com/demos/azimuth/" target="_blank" rel="noopener nofollow">Azimuth theme</a>
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
